language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    include:
        - php: 5.4
          env: dependencies=lowest

before_script:
    - composer self-update
    - composer --dev install
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script: bin/phpspec run -fpretty --verbose
